[build]
  command = "npm run build:client"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "18"

# Static pages should be served as-is
[[redirects]]
  from = "/registeration/"
  to = "/registeration/index.html"
  status = 200

[[redirects]]
  from = "/cart/"
  to = "/cart/index.html"
  status = 200

# API routes should not be redirected
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# All other routes go to React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
